### PR TITLE
FIX: Remove callable from plan signature for qserver

### PR DESCRIPTION
**Pull request by maffettone**
This removes the  explicit default `trigger_and_read` from the function definition signature.

## Description

Instead of the callable in the signature, the default is set to `None`, and then checked to replace with `trigger_and_read`. 

## Motivation and Context

This issue pops up when importing these plans into the startup files used by the queue-server. 
- `one_nd_step`
- `one_1d_step`
- `one_shot`

```
# [E 2023-04-01 17:25:38,999 bluesky_queueserver.manager.worker] Failed to start RE Worker environment. Error while loading startup code: Failed to create description of plan 'one_1d_step': Parameter 'take_reading': The expression (<function trigger_and_read at 0x7ff0ae7ab640>) can not be evaluated with 'ast.literal_eval()': unsupported type of default value..
# Traceback (most recent call last):
#   File "/nsls2/conda/envs/2023-1.3-py310-tiled/lib/python3.10/site-packages/bluesky_queueserver/manager/profile_ops.py", line 2582, in convert_expression_to_string
#     ast.literal_eval(s_value)
#   File "/nsls2/conda/envs/2023-1.3-py310-tiled/lib/python3.10/ast.py", line 64, in literal_eval
#     node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
#   File "/nsls2/conda/envs/2023-1.3-py310-tiled/lib/python3.10/ast.py", line 50, in parse
#     return compile(source, filename, mode, flags,
#   File "<unknown>", line 1
#     <function trigger_and_read at 0x7ff0ae7ab640>
#     ^
# SyntaxError: invalid syntax
```

## How Has This Been Tested?

Copied these new plans into a queserver test environment.

### CODE REVIEW

**Comment by prjemian** [comment]
> when importing these plans

Which plans are _these_?

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
These plans do not generate runs so I am a _bit_ worried that QS needs to be aware of them, but moving to `None` as the default and internal re-mapping is better anyway.

**Comment by maffettone** [comment]
@prjemian Updated the text to be more specific. 
@tacaswell In general it's less of an issue in putting these directly on the queue without wrapping them in a run, and more of an issue in queserver failing to load a startup profile that has these in the namespace.

**Review by mrakitin — APPROVED** [review]
Thanks, @maffettone! Looks good to me.

Are the unrelated CI failures explainable?
```py
RE = <bluesky.run_engine.RunEngine object at 0x7f104f27b520>
db = <databroker.v1.Broker object at 0x7f104f2750a0>

    def test_relative_pseudo(hw, RE, db):
    
        RE.subscribe(db.insert)
        p = hw.pseudo3x3
        p.set(1, 1, 1)
        base_pos = p.position
    
        # this triggers the merging code path
        rs = RE(bp.relative_inner_product_scan([p],
                                               5,
                                               p.pseudo1, -1, 1,
                                               p.pseudo2, -2, -1))
    
        if RE.call_returns_result:
            uid = rs.run_start_uids[0]
        else:
            uid = rs[0]
    
>       tb1 = db[uid].table().drop('time', 1)
E       TypeError: drop() takes from 1 to 2 positional arguments but 3 were given

bluesky/tests/test_plans.py:166: TypeError
```

**Comment by tacaswell** [comment]
I have no good theory on the failure.  At first I thought it was a pandas 2.0 thing, but the passing runs also used pandas 2.0...

**Comment by tacaswell** [comment]
no, I am wrong.  On the passing tests for some reason we are installing pandas 2.0 and then forcing back to 1.5.3.  I'll add a commit to this PR fixing the issue.

**Comment by tacaswell** [comment]
powercycled to restart CI.

**Pull request merged**
