### PR TITLE
re-apply the livescatter axes fix from PR 1523

### PR DESCRIPTION
**Pull request by stan-dot**
## Description

re-applied changed from https://github.com/bluesky/bluesky/pull/1523

### CODE REVIEW

**Review by maffettone — APPROVED** [review]
Looks good, not sure how to enhance coverage on mpl.

**Comment by stan-dot** [comment]
@tacaswell can we merge this as-is? or alternatively how to increase the coverage from the current value:

`[src/bluesky/callbacks/mpl_plotting.py](https://app.codecov.io/gh/bluesky/bluesky/pull/1787/blob/src/bluesky/callbacks/mpl_plotting.py)
4
81.05%
0.00%
0.00%`

[source](https://app.codecov.io/gh/bluesky/bluesky/pull/1787?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=bluesky)

**Comment by maffettone** [comment]
@stan-dot @tacaswell Added a test that increases coverage over the conditionals and attrs. Is green, merge?

**Comment by stan-dot** [comment]
this looks great! Thanks @maffettone , it's mergeable as far as I am concerned

**Pull request merged**
