### PR TITLE
FIX: regression in validating the per_step signature for 1d case

### LINKED ISSUE #1295: Old per_step scans now invalid
`per_step` scans have closely regulated signatures. The regulator changed.

## Expected Behavior

per_step scans that worked in `bluesky=1.5.5` should work in `bluesky=1.6.0` or have clear instructions to upgrade

## Current Behavior

The signatures of `one_nd_step` and `one_1d_step` were changed, but these signatures are being used to check if a user's `per_step` function is valid. https://github.com/bluesky/bluesky/blob/feb8e7951276be3fe7714035faf8756a5fb1f4f1/bluesky/plans.py#L922-L944 

Note how the error message states the old signature, but the code requires the new one.

## Possible Solution

Either the error message should be changed to reflect the new signature, or the old signature should still be valid.

## Steps to Reproduce (for bugs)

1. Run any scan with a previously-working per_step arg

## Context

I want to upgrade to `bluesky=1.6.0` when available

## Your Environment

`bluesky=1.6.0rc4` installed in dev mode

### PR DESCRIPTION
**Pull request by tacaswell**
closes #1295

Fixes a regression in how we validate the per_step functions

Added tests of both passing and failing signatures

### CODE REVIEW

**Comment by danielballan** [comment]
New tests fail.

**Comment by tacaswell** [comment]
```

E           AssertionError: Pattern
'per_step must be a callable with the signature <Signature (detectors, step, pos_cache)> or <Signature (detectors, motor, step)>.' not found in
'per_step must be a callable with the signature <Signature (detectors, step, pos_cache)> or <Signature (detectors, motor, step)>.'
```

sigh.

**Comment by tacaswell** [comment]
Lets see if that works any better.

**Comment by tacaswell** [comment]
The missing lines in the patch are the never-run bodies of the dead functions...

**Comment by klauer** [comment]
So for this to work, is it required for the parameters in our per_step functions to have the exact names `['detectors', 'motor', 'step']`?

**Comment by danielballan** [comment]
Yes, but that has always been true.

**Comment by klauer** [comment]
Interesting - I (obviously) didn't recall that...

**Comment by danielballan** [comment]
We checked for exactly signature equality.

https://github.com/bluesky/bluesky/blob/75bb50d4116560851bafe663d2a227348808701e/bluesky/plans.py#L717-L721

This is more relaxed because it allows for `per_step` to have additional optional parameters, which we will ignore.

**Comment by danielballan** [comment]
Looks like we introduced the strict checking in v1.2.0 when `one_nd_step` and `one_1d_step` were unified. Before 1.2.0 there was no signature check.

**Comment by klauer** [comment]
@danielballan I believe you 😄 - I just didn't remember that.

**Comment by tacaswell** [comment]
I was also surprised, but went with preserving as much of the same functionality as before.

This may still be a bit _too_ permissive, but you will have to be obtuse to run into those issues.

**Pull request merged**
