### PR TITLE
Support adaptive fly scans.

### PR DESCRIPTION
**Pull request by danielballan**
In step scans, the plans can access the data like:

```py
reading = yield from bps.read(obj)
```

This PR enables this for fly scans:

```py
payload = yield from bps.collect(obj)
```

In situations where the payload is too large to accumulate in memory,
this new option opts out of accumulation and causes the coroutine to
return ``None``.

```py
yield from bps.collect(obj, return_payload=False)
```

### CODE REVIEW

**Comment by danielballan** [comment]
New commits look good, @tacaswell. Thanks.

**Comment by danielballan** [comment]
Extra context for posterity: this was written for / tested with https://github.com/danielballan/adaptive-with-delay

**Comment by tacaswell** [comment]
The very wrong docstring on `_collect` was copy-pasta errors from the bundler refactor, sorry about that.

**Comment by danielballan** [comment]
"Copy-pasta errors" is a typo for the ages.

**Comment by prjemian** [comment]
🍝

**Pull request merged**
