### PR TITLE
use tmpdir for ophyd sim path so pytest cleans up properly

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@NSLS-II/dama ready for review! (this needed the ophyd change)

**Comment by tacaswell** [comment]
This probably has to wait until we do an ophyd release?

**Comment by CJ-Wright** [comment]
Ah ok, I thought you were installing on travis from source.

**Comment by tacaswell** [comment]
I think we tagged a new ophyd release

**Comment by CJ-Wright** [comment]
@tacaswell this works now! Yey!

**Pull request merged**
