### PR TITLE
Backport #1369 to v1.5.x

### PR DESCRIPTION
**Pull request by jklynch**
Backport of #1369.

### CODE REVIEW

**Comment by jklynch** [comment]
CI failed on python 3.6 with what looks like a server issue. (?)

**Comment by danielballan** [comment]
Agreed. Restarted that build.

**Comment by jklynch** [comment]
@danielballan I could not restart the build, but I have been able to do that in the past maybe just for other repositories. Do you know why?

**Comment by danielballan** [comment]
Double check that you are still signed into Travis. When this happens to me, it’s because my session with Travis has expired.

**Pull request merged**
