### PR TITLE
API: make zict an optional dependency and update docs

### LINKED ISSUE #1577: bug: Incompatible with zict 3.0.0
While looking at merging a PR it was found that CI jobs were failing as they were using the latest (breaking) version of zict.

## Expected Behavior
Job should not fail

## Current Behavior
CI Job fails.

## Possible Solution
Someone should investigate why it's failing, exactly; we know it's a zict problem but not sure how/why.

## Steps to Reproduce (for bugs)
see https://github.com/bluesky/bluesky/pull/1575

## Context
I have a small PR (one line change) open to change something about bluesky FailedStatus tracebacks. The CI jobs for this are all failing. 

Upon closer inspection the culprit is the zict library 3.0.0 upgrade.

## Your Environment
See  https://github.com/bluesky/bluesky/pull/1575

A PR to temporarily pin zict for now has been opened.

### PR DESCRIPTION
**Pull request by tacaswell**
Also xfail the one bad test based on version gating.

closes #1577

## Motivation and Context

zict 3 has a behavior change that breaks one of our tests (and using two bsui sessions), see #1577 for details (thank you @dmgav for sorting out the problem!).

Pinning back zict is causing other conflict with dask and we should start to move away from it all together.

@genematx I know you are working on document RedisJsonDict, hopefully this does not step on what you are doing too much.

## How Has This Been Tested?

locally running tests

### CODE REVIEW

**Comment by prjemian** [comment]
I've got an alternative we're just starting to test. It's file-backed rather than redis. Does not use zict. It uses YAML and MutableMapping.

**Comment by tacaswell** [comment]
If there are better alternatives on the way I still think we should merge this as-is and then update as the new things are ready.

**Comment by prjemian** [comment]
https://github.com/BCDA-APS/bs_model_instrument/blob/main/src/instrument/utils/stored_dict.py

**Comment by tacaswell** [comment]
The code that is not being covered is the error message, however I don't think it is worth setting up an additional full run without zict installed to catch that.

**Comment by tacaswell** [comment]
I marked this as API because it may catch someone out, but I think it is OK to do this in a 1.13.1 release.

**Review by danielballan — APPROVED** [review]
Let’s tag and release an RC first and crank the tests on Ophyd and Ophyd-async.

**Pull request merged**
