### PR TITLE
ENH: implement human-readable repr for `PeakStats`

### PR DESCRIPTION
**Pull request by mrakitin**
Implements human-readable `__repr__` for the `PeakStats` (continuation of improvements of #1478).

## Description

This PR adds the `__repr__` and `__dict__` methods to easily see the data for the stats and derivative stats.
Used a hint from https://stackoverflow.com/a/34166604 regarding `._asdict()` for namedtuple objects.

## Motivation and Context

The previous way of reporting the PeakStats information was hard to use. Example from @gfreychet:
```py
bec._peak_stats
Out[29]: {'bd52e883-7422-4b3b-94a4-a4b5adbaaebc': {'pil1M_stats1_total': <bluesky.callbacks.fitting.PeakStats at 0x7f046f6b9850>}}
```
With this update:
```py
In [15]: bec._peak_stats
Out[15]:
{'f38cbe6a-029f-493a-a07c-73c4eb45a799': {'det': {'derivative_stats': {'cen': 0.0999999999999998,
                        'com': -0.8,
                        'crossings': array([0.1]),
                        'fwhm': None,
                        'lin_bkg': None,
                        'max': (-0.8, 0.1196183773610574),
                        'min': (1.0, -0.1196183773610574),
                        'x': array([-0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]),
                        'y': array([ 0.11961838,  0.10912117,  0.08784613,  0.05708233,  0.01980133,
         -0.01980133, -0.05708233, -0.08784613, -0.10912117, -0.11961838])},
   'stats': {'cen': 5.551115123125783e-17,
             'com': 0.0,
             'crossings': array([-0.65865934,  0.65865934]),
             'fwhm': 1.3173186844780238,
             'lin_bkg': None,
             'max': (0.0, 1.0),
             'min': (-1.0, 0.6065306597126334)}}}}
```

## How Has This Been Tested?

Tested locally.

### CODE REVIEW

**Comment by mrakitin** [comment]
attn @gfreychet

**Comment by mrakitin** [comment]
Hi All, any chance it could be reviewed/merged this week?

**Review by ZLLentz — COMMENTED** [review]
I personally think this looks good and is a large improvement over the existing repr, but I haven't used enough of `PeakStats` myself to give a full opinion/review.

**Comment by prjemian** [comment]
Can someone post an example of the repr from the current code base?  Is the example above the most recent example.

**Comment by mrakitin** [comment]
> Can someone post an example of the repr from the current code base? Is the example above the most recent example.

This is the first code block in the "Motivation and Context" section of the description:
```py
bec._peak_stats
Out[29]: {'bd52e883-7422-4b3b-94a4-a4b5adbaaebc': {'pil1M_stats1_total': <bluesky.callbacks.fitting.PeakStats at 0x7f046f6b9850>}}
```

**Comment by prjemian** [comment]
I meant to ask: What does the new version look like?

**Comment by mrakitin** [comment]
The second block from the description is for the repr with the code from this PR. That should be current.
```py
In [15]: bec._peak_stats
Out[15]:
{'f38cbe6a-029f-493a-a07c-73c4eb45a799': {'det': {'derivative_stats': {'cen': 0.0999999999999998,
                        'com': -0.8,
                        'crossings': array([0.1]),
                        'fwhm': None,
                        'lin_bkg': None,
                        'max': (-0.8, 0.1196183773610574),
                        'min': (1.0, -0.1196183773610574),
                        'x': array([-0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ]),
                        'y': array([ 0.11961838,  0.10912117,  0.08784613,  0.05708233,  0.01980133,
         -0.01980133, -0.05708233, -0.08784613, -0.10912117, -0.11961838])},
   'stats': {'cen': 5.551115123125783e-17,
             'com': 0.0,
             'crossings': array([-0.65865934,  0.65865934]),
             'fwhm': 1.3173186844780238,
             'lin_bkg': None,
             'max': (0.0, 1.0),
             'min': (-1.0, 0.6065306597126334)}}}}
```

**Review by prjemian — APPROVED** [review]
LGTM!

**Comment by mrakitin** [comment]
Thanks, @prjemian! I'll use the "Before" and "After" titles for clarity next time.

**Comment by prjemian** [comment]
Thanks for clarifying.  Since there were commits after, it was not obvious that the second example was the final result.

**Comment by mrakitin** [comment]
> Thanks for clarifying. Since there were commits after, it was not obvious that the second example was the final result.

FWIW, these commits are mostly related to CI/tests, not the changed code.

**Comment by mrakitin** [comment]
FYI: I've added a commit https://github.com/bluesky/bluesky/pull/1486/commits/48b0a538fc8223b384d5629acdc20e354d3d9698 to add better visibility of the `PeakStats` attributes when doing `dir(ps)` (and the tab-completion in IPython). Here are examples (before and after):

### Preparation
```py
In [1]: from bluesky.callbacks.best_effort import BestEffortCallback
   ...: from databroker import Broker
   ...: db = Broker.named("smi")
   ...: hdr = db["<UID>"]
   ...: hdr.table()
   ...: bec = BestEffortCallback(calc_derivative_and_stats=True)
   ...: for name, doc in hdr.documents():
   ...:     bec(name, doc)
...

In [2]: ps = bec._peak_stats["<descriptor-UID>"]["pil1M_stats1_total"]
```

### Before:
```py
In [3]: dir(ps)
Out[3]:
['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_calc_stats',
 '_dispatch',
 'bulk_datum',
 'bulk_events',
 'compute',
 'datum',
 'datum_page',
 'descriptor',
 'emit',
 'event',
 'event_page',
 'log',
 'reset',
 'resource',
 'start',
 'stop']
```

### After:
```py
In [3]: dir(ps)
Out[3]:
['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_calc_stats',
 '_dispatch',
 'bulk_datum',
 'bulk_events',
 'cen',
 'com',
 'compute',
 'crossings',
 'datum',
 'datum_page',
 'derivative_stats',
 'descriptor',
 'emit',
 'event',
 'event_page',
 'fwhm',
 'lin_bkg',
 'log',
 'max',
 'min',
 'reset',
 'resource',
 'start',
 'stats',
 'stop',
 'x',
 'y']
```

**Review by gfreychet — APPROVED** [review]
After testing the code at SMI beamline, all worked as it should and the derivative calculation works as expected.
The last addition of derivative_stats as a key makes the reading easier (thanks Maskim)

**Comment by gfreychet** [comment]
@mrakitin I have been playing with the new peak_stats implemented in bec and it works nicely. I have one modification to suggest, which is to have the x and y values stored in stats. Currently, I am trying to build an efficient procedure for the sample alignment of gisaxs. I need to scan sample height and angle and find the maximum for the angle and the inflection point for the height (that is why I needed the derivative). I want to be able to display the position of max / cen / com calculated superposed with either x, y or the derivated x, y. Currently in bec._stats only the derivated x and y are stored, not the initial x and y. I would like a time efficient way to access the x and y without having to open db.table which takes 3s or so

**Comment by mrakitin** [comment]
@gfreychet was testing the feature on the beamline with my remote assistance, and earlier posted a comment (currently removed) about missing `x` and `y` attributes in the `ps.stats` object (an attribute of the `ps` object in my comment above). The concern was that they are not exposed the same way as it was done for the `derivative_stats` attribute. The reason is that I did not want to duplicate the already existing `ps.x_data` and `ps.y_data` fields, so the `ps.stats` object's fields are slightly different than the `ps.derivative_stats`' fields. Guillaume told me that it works for his purposes.

I just added the `x_data` and `y_data` attributes to the `__slots__` via https://github.com/bluesky/bluesky/pull/1486/commits/5998ea01046ab31859ad3dba6e11dbbd1da0376d for easier discovery on the client side:
```py
n [4]: dir(ps)
Out[4]: 
['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_calc_stats',
 '_dispatch',
 'bulk_datum',
 'bulk_events',
 'cen',
 'com',
 'compute',
 'crossings',
 'datum',
 'datum_page',
 'derivative_stats',
 'descriptor',
 'emit',
 'event',
 'event_page',
 'fwhm',
 'lin_bkg',
 'log',
 'max',
 'min',
 'reset',
 'resource',
 'start',
 'stats',
 'stop',
 'x',
 'x_data',
 'y',
 'y_data']
```

Ready for final review.

**Comment by mrakitin** [comment]
Hi everyone, is there anything that I should address? I would like to merge it by Friday this week.

**Comment by prjemian** [comment]
Very timely.  APS beam line 29ID wants to lineup on the derivative of a scan such as this one (so we want a release with the PeakStats derivative code in it):

APS-29id-scan

**Comment by mrakitin** [comment]
Any objections to merging it today?

**Review by dmgav — APPROVED** [review]

**Comment by mrakitin** [comment]
Thanks, @dmgav!

**Pull request merged**
