### PR TITLE
DOC: document pycertifspec as hardware interface

### PR DESCRIPTION
**Pull request by untzag**
Document additional hardware interface package.

### CODE REVIEW

**Review by mrakitin — APPROVED** [review]
Thanks, @untzag! That reminds me of your suggestion to add https://github.com/NSLS-II/sirepo-bluesky (will submit a separate PR).

**Comment by tacaswell** [comment]
I think we should get @SEBv15 to sign off on this before we merge.

**Comment by prjemian** [comment]
> I think we should get @SEBv15 to sign off on this before we merge.

Let's make that separate issue.  Related, but separate for just this reason.

**Comment by SEBv15** [comment]
I don't have any issues with my library being listed as an interface. However, maybe consider adding a note that it is still very much in an experimental stage.

**Pull request merged**
