### PR TITLE
add reset user position stub

### PR DESCRIPTION
**Pull request by stan-dot**
## Description

Adding a new stub representing a correction mechanic to the plan stubs list.

## Motivation and Context

As discussed in [the prior PR](https://github.com/bluesky/bluesky/pull/1301) a stub like this is useful in long-running experiments to prevent the RE from staying in an erroneous state.

## How Has This Been Tested?

Not yet.

### CODE REVIEW

**Comment by callumforrester** [comment]
@stan-dot Please could you add further clarification on the purpose of this plan stub? I'm not sure it should require `RunEngine` changes, if it does, can we find a more general solution than one that has to make the `RunEngine` aware of the `Positioner` API?

**Comment by stan-dot** [comment]
@callumforrester  I updated the issue description

**Comment by stan-dot** [comment]
should the idea be reviewed as ok, a test can be done

**Comment by callumforrester** [comment]
I don't know enough about the background so I'll defer to others' opinions

**Comment by stan-dot** [comment]
todo: add tests for beyond the happy path

**Comment by stan-dot** [comment]
@coretl  given the `Locatable` interface, as expressed in https://github.com/bluesky/ophyd-async/pull/541 maybe this would sooner belong in ophyd-async?

**Comment by coretl** [comment]
> @coretl given the `Locatable` interface, as expressed in [bluesky/ophyd-async#541](https://github.com/bluesky/ophyd-async/pull/541) maybe this would sooner belong in ophyd-async?

Personally I would agree with the approach in https://github.com/bluesky/bluesky/pull/1301#issuecomment-587965339. To mitigate plan interruption we could put motor record back into "SET" if not already there in `stage`, so that we will recover without human intervention.

If that is not acceptable then we need a new protocol to cover what is needed with a new method (which you called `set_current_position`) to set the current position of the motor. This should be `MaybeAsync`. `Locatable` should be used to get the current position of the motor in the plan stub.

**Comment by stan-dot** [comment]
> To mitigate plan interruption we could put motor record back into "SET" if not already there in stage, so that we will recover without human intervention.

@coretl do you mean here?

> put motor record back into "SET" if not already there in stage,

is it in the ophyd_asycn Motor class, in an instance method 'stage' or 'set', or just in a stub, or in a plan when we expect that something *might* go wrong?

**Comment by coretl** [comment]
> > To mitigate plan interruption we could put motor record back into "SET" if not already there in stage, so that we will recover without human intervention.
> 
> @coretl do you mean here?
> 
> > put motor record back into "SET" if not already there in stage,
> 
> is it in the ophyd_asycn Motor class, in an instance method 'stage' or 'set', or just in a stub, or in a plan when we expect that something _might_ go wrong?

https://epics.anl.gov/bcda/synApps/motor/motorRecord.html#Fields_calib

```python
def __init__(self, prefix: str):
    ...
    self.set_use = epics_signal_rw(MotorSetUse, prefix + ".SET")
    ...

async def stage(self):
    await self.set_use.set(MotorSetUse.USE)

async def set(self, value):
    status = self.position.set(value)
    ...
```

Then we can continue doing thing like this in the plan stub:
```python
def set_motor_position(motor: Motor, position: float):
    def make_motor_usable():
        yield from abs_set(motor.set_use, MotorSetUse.SET)

    def inner():
        yield from abs_set(motor.set_use, MotorSetUse.USE)
        yield from abs_set(motor.position, position)

    return (yield from finalize_wrapper(inner(), make_motor_usable()))
```

So unless the RE crashes, or is halted without doing cleanup, then motors will always be in USE mode no matter what happens when running `set_motor_position`, but if the `Motor` Device does encounter a motor in SET mode, it will be set back to USE mode in `motor.stage()`

**Comment by stan-dot** [comment]
I see now, thanks @coretl 

regarding the naming, I am not sure what is the tango equivalent, but I feel that `use_set` is unintuitive and coupled with `EPICS`. The `stage` verb is available right there, could we explore naming the property something like `staging_status`?

**Comment by coretl** [comment]
> regarding the naming, I am not sure what is the tango equivalent, but I feel that `use_set` is unintuitive and coupled with `EPICS`. The `stage` verb is available right there, could we explore naming the property something like `staging_status`?

I assume you mean `set_use`. This is most definitely EPICS specific, because we are referring to the `.SET` field of the motor record which I linked above. It could be named `mode` or `set_use_mode` if that is better, but it must be an enum:
```python
class MotorSetUse(str, Enum):
    use = "Use"
    set = "Set"
```
because that is what the motor record defines it to be

**Comment by prjemian** [comment]
In the apstools package, I named the same operations as
`redefine_motor_position`.

https://bcda-aps.github.io/apstools/latest/api/_utils.html#apstools.utils.misc.redefine_motor_position

**Comment by stan-dot** [comment]
@callumforrester , I didn't construe this (https://github.com/bluesky/bluesky/pull/1778#issuecomment-2321736240) as supportive of using EPICS terminology, and I mentioned the EPICS coupling as a negative feature of the solution, as I don't know what does TANGO use

**Comment by coretl** [comment]
Closing as not planned

**Pull request closed without merging**
