### PR TITLE
Add collated documentation and type hints

### LINKED ISSUE #1775: Add documentation snippets and type hints
Make a joint PR of the doc PRs
1. https://github.com/bluesky/bluesky/pull/1341
2. https://github.com/bluesky/bluesky/pull/1503
3. https://github.com/bluesky/bluesky/pull/1546

_Originally posted by @stan-dot in https://github.com/bluesky/bluesky/issues/1757#issuecomment-2264879706_

### PR DESCRIPTION
**Pull request by stan-dot**
Fixes #1775

## Description
Collates the documentation updates from 3 different past PRs.

### CODE REVIEW

**Comment by callumforrester** [comment]
Does this provide anything that https://github.com/bluesky/bluesky/pull/1600 and #1712 don't?

**Comment by stan-dot** [comment]
it clearly does - the cycler and progress bar docs. The case of the plans.py is different, as #1712 seems to make heavy use of types

**Comment by stan-dot** [comment]
the failing test is unparseable



image

**Comment by stan-dot** [comment]
the lint error is mostly from `snake_cyclers`

@danielballan what do you think?


image

**Comment by stan-dot** [comment]
```bash

 /home/runner/work/bluesky/bluesky/src/bluesky/utils/__init__.py:docstring of bluesky.utils.ProgressBar:1: WARNING: duplicate object description of bluesky.utils.ProgressBar, other instance in generated/bluesky.utils.ProgressBar, use :no-index: for one of them
/home/runner/work/bluesky/bluesky/src/bluesky/utils/__init__.py:docstring of bluesky.utils.ProgressBarManager:1: WARNING: duplicate object description of bluesky.utils.ProgressBarManager, other instance in generated/bluesky.utils.ProgressBarManager, use :no-index: for one of them
looking for now-outdated files... none found


```


why does it compare against the`generated` folder?

**Comment by stan-dot** [comment]
similar issues

https://github.com/sphinx-doc/sphinx/issues/10348

**Review by coretl — APPROVED** [review]
Looks ok to me

**Pull request merged**
