### PR TITLE
backport PR 1338 to 1.5.x branch

### PR DESCRIPTION
**Pull request by jklynch**
This PR backports #1338 to the 1.5.x branch.

### CODE REVIEW

**Comment by jklynch** [comment]
The CI failure is related to `suitcase.jsonl`, which I had to install to get the tests to pass on my computer, but then I didn't think about it anymore.
```
==================================== ERRORS ====================================
____________________ ERROR at setup of test_table_external _____________________
request = <SubRequest 'db' for <Function test_table_external>>
    @pytest.fixture(scope='function')
    def db(request):
        """Return a data broker
        """
>       from databroker.tests.utils import build_sqlite_backed_broker
bluesky/tests/conftest.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    import os
    from pathlib import Path
    from subprocess import Popen
    import shutil
    import tempfile
    import time
    import uuid
    import pytest
    import ophyd.sim
    import tzlocal
    
    from databroker import v0, v1
    from databroker.headersource import HeaderSourceShim
    from databroker.eventsource import EventSourceShim
    from .._drivers import jsonl
    from .._drivers import mongo_normalized
    from .._drivers import mongo_embedded
    from .. import core
>   import suitcase.jsonl
E   ModuleNotFoundError: No module named 'suitcase.jsonl'
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/databroker/tests/utils.py:19: ModuleNotFoundError
______________________ ERROR at setup of test_broker_base ______________________
```

**Comment by tacaswell** [comment]
I would prefer we install the required suitcase packages on travis.

**Comment by danielballan** [comment]
Could you place the requirement in `requirements-dev.txt` instead of in `travis.yml` so that it will install for local development as well?

**Comment by danielballan** [comment]
Oh, I see you originally did that in 4ad70b6. Why the change in 09652cc?

**Comment by jklynch** [comment]
I think I read Tom's comments out-of-order.

**Pull request merged**
