### PR TITLE
ENH: RunEngine as a service

### PR DESCRIPTION
**Pull request by danielballan**
If anyone thinks that "bluesky as a service" will solve a problem that they currently have, here is a workable approach.

This is alpha code, developed in three hours on a whim. I'm putting this out there as is, merely to demonstrate that the bluesky model is amenable to server/client interaction. Use at your own risk.
## Model
1. The server runs a only-slightly-customized RunEngine, configured with a dictionary that maps JSON-friendly tokens like `'motor'` to Python Device objects like `motor`.
2. The client sends "messages" as JSON objects.
3. The server decodes these "messages" into actual `Msg`'s and sends them to the RunEngine. It sends the RunEngine's response back to the client (as JSON).

The server/client communication is implemented using the zmq PAIR model: a server in two-way communication with exactly one client.
## Capabilities

This server implementation already supports:
- adaptive plans
- pause/resume/abort
- reporting and automatically recovering from arbitrary exceptions in the RunEngine

It does not yet support:
- pausing from a suspended state
- probably other stuff I haven't thought of

This client is just a quick sketch. Any tcp client that can send JSON is workable.
## Demo

The plan (from bluesky/examples/client.py)

``` python
plan = [
        # start simple :- )
        {'msg': {'command': 'null', 'obj': None, 'args': [], 'kwargs': {}}},

        # a pause message pauses the RunEngine
        {'msg': {'command': 'pause', 'obj': None, 'args': [], 'kwargs': {}}},
        # and it can be resumed
        {'change_state': 'resume'},

        # objects like motor are mapped with string idenfiers
        {'msg': {'command': 'set', 'obj': 'motor', 'args': [5], 'kwargs': {}}},

        # pause again, and this time abort
        {'msg': {'command': 'pause', 'obj': None, 'args': [], 'kwargs': {}}},
        {'change_state': 'abort'},
        # the RunEngine is idle, but the server is ready to send it new
        # messages and put it back into a running state
        {'msg': {'command': 'null', 'obj': None, 'args': [], 'kwargs': {}}},

        # this raises a TypeError, but the server recovers...
        {'msg': {'command': 'set', 'obj': 'motor', 'args': [], 'kwargs': {}}},
        # ... and this is processed
        {'msg': {'command': 'null', 'obj': None, 'args': [], 'kwargs': {}}}]
```

This is the stdout from the server. The lines beginning with all-caps are from the server itself; the rest is from a RunEngine.msg_hook.

```
$ python bluesky/examples/server.py
Server is ready to receive messages.
SENDING: {"state": "idle"}
RECEIVED: {'msg': {'obj': None, 'kwargs': {}, 'args': [], 'command': 'null'}}
null: (None), (), {}
SENDING: {'response': 'None'}
RECEIVED: {'msg': {'obj': None, 'kwargs': {}, 'args': [], 'command': 'pause'}}
pause: (None), (), {}
Pausing...
SENDING: {"state": "paused"}
RECEIVED: {'change_state': 'resume'}
null: (None), (), {}
SENDING: {'response': 'None'}
RECEIVED: {'msg': {'obj': 'motor', 'kwargs': {}, 'args': [5], 'command': 'set'}}
set: (mover: motor), (5,), {}
SENDING: {'response': 'mover: motor'}
RECEIVED: {'msg': {'obj': None, 'kwargs': {}, 'args': [], 'command': 'pause'}}
pause: (None), (), {}
Pausing...
SENDING: {"state": "paused"}
RECEIVED: {'change_state': 'abort'}
Aborting....
SENDING: {"state": "idle"}
RECEIVED: {'msg': {'obj': None, 'kwargs': {}, 'args': [], 'command': 'null'}}
null: (None), (), {}
SENDING: {'response': 'None'}
RECEIVED: {'msg': {'obj': 'motor', 'kwargs': {}, 'args': [], 'command': 'set'}}
set: (mover: motor), (), {}
EXCEPTION RAISED: set() missing 1 required positional argument: 'val'
The RunEngine will be re-started....
SENDING: {"exception": "TypeError(\"set() missing 1 required positional argument: 'val'\",)", "state": "idle"}
RECEIVED: {'msg': {'obj': None, 'kwargs': {}, 'args': [], 'command': 'null'}}
null: (None), (), {}
SENDING: {'response': 'None'}
```

This is the stdout from the client:

```
$ python bluesky/examples/client.py
RECEIVED: "{\"state\": \"idle\"}"
SENDING: {"msg": {"args": [], "command": "null", "kwargs": {}, "obj": null}}
RECEIVED: {"response": "None"}
SENDING: {"msg": {"args": [], "command": "pause", "kwargs": {}, "obj": null}}
RECEIVED: "{\"state\": \"paused\"}"
SENDING: {"change_state": "resume"}
RECEIVED: {"response": "None"}
SENDING: {"msg": {"args": [5], "command": "set", "kwargs": {}, "obj": "motor"}}
RECEIVED: {"response": "mover: motor"}
SENDING: {"msg": {"args": [], "command": "pause", "kwargs": {}, "obj": null}}
RECEIVED: "{\"state\": \"paused\"}"
SENDING: {"change_state": "abort"}
RECEIVED: "{\"state\": \"idle\"}"
SENDING: {"msg": {"args": [], "command": "null", "kwargs": {}, "obj": null}}
RECEIVED: {"response": "None"}
SENDING: {"msg": {"args": [], "command": "set", "kwargs": {}, "obj": "motor"}}
RECEIVED: "{\"exception\": \"TypeError(\\\"set() missing 1 required positional argument: 'val'\\\",)\", \"state\": \"idle\"}"
SENDING: {"msg": {"args": [], "command": "null", "kwargs": {}, "obj": null}}
```

### CODE REVIEW

**Comment by tacaswell** [comment]
The other half of this is https://github.com/NSLS-II/bluesky/pull/395 which use zmq to do broadcast Documents, @klauer 's PV publisher which pushes uids to a PV, or something with v4 normative types to broadcast the full documents.

I think with this set of things we can completely pick apart the RE loop. the plan iteration, and the Document handling.

**Comment by danielballan** [comment]
@dchabot Great. Speak up if you take it for a spin and have questions/requests/concerns.

**Comment by tacaswell** [comment]
Discussing this with @ronpandolfi have the following proposals:

 - both sides (client and server) have live ohpyd objects
    - this can be dicey for synthetic devices as they will not be synced through the ground-truth of the hardware system.  
    - Pseudo devices should be fine as the real axes will be synced which will for the pseudo axes to stay synced
  - the server owns the device configuration and informs the clients what devices it has by pushing name + pickle to it on connection.
   - maybe let the client ask for extra signals / devices to be added to the server
   - need to make sure the server RE state is propogated back to the client (via side-band)
   - need to add the pause/cancel from suspend logic (via same side-band?)

**Comment by danielballan** [comment]
These ideas are being developed in a separate repository, https://github.com/bluesky/bluesky-queueserver.

**Pull request closed without merging**
