### PR TITLE
TST: make three-hit-sigint tests less prone to race conditions

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by ke-zhang-rd** [comment]
Below is test result from my local Mac.
```
bluesky/tests/test_run_engine.py::test_sigint_three_hits 1.865701051428914e-05:  about to start the timers
0.0009773949859663844:  all timers started
0.0010032859863713384:  about to start RE
0.0026459249784238636:  about to move the motor
16:42:23.210179 set               -> motor           args: (1,), kwargs: {'group': '91ea55eb-46dd-41eb-ae18-765afa31aaf2'}
16:42:23.210865 wait              -> None            args: (), kwargs: {'group': '91ea55eb-46dd-41eb-ae18-765afa31aaf2'}
0.05335330398520455:  the 1 timer has fired
0.10122823598794639:  the 2 timer has fired
0.10692742798710242:  sig int 0 of timer 1
A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
0.15411524596856907:  sig int 0 of timer 2
0.15420077601447701:  the 3 timer has fired
trying a second time
Pausing...
0.15574877697508782:  out of RE
0.15576799999689683:  about RE.abort
Aborting: running cleanup and marking exit_status as 'abort'...
16:42:23.364328 set               -> motor           args: (0,), kwargs: {'group': '749b1823-7c20-440b-a345-d4bd6fcdc24c'}
16:42:23.364831 wait              -> None            args: (), kwargs: {'group': '749b1823-7c20-440b-a345-d4bd6fcdc24c'}
0.1593770440085791:  sig int 1 of timer 1
0.20751204201951623:  sig int 0 of timer 3
0.20763151202118024:  sig int 1 of timer 2
0.21254824701463804:  sig int 2 of timer 1
0.25972816097782925:  sig int 1 of timer 3
0.25982351996935904:  sig int 2 of timer 2
0.31038607901427895:  sig int 2 of timer 3
[E 16:42:23.870 run_engine:1515] Run aborted
    Traceback (most recent call last):
      File "/Users/kz2249/bluesky/bluesky/run_engine.py", line 1391, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/Users/kz2249/bluesky/bluesky/preprocessors.py", line 501, in finalize_wrapper
        ret = yield from plan
      File "/Users/kz2249/bluesky/bluesky/tests/test_run_engine.py", line 606, in self_sig_int_plan
        yield from abs_set(motor, 1, wait=True)
      File "/Users/kz2249/bluesky/bluesky/plan_stubs.py", line 182, in abs_set
        yield Msg('wait', None, group=group)
    bluesky.utils.RequestAbort
0.6657003639847971:  done RE.abort
PASSED
```

**Comment by tacaswell** [comment]
Something is very odd about the OSX instances we have access to on travis this is the failed test (with all the logging prints from https://travis-ci.org/bluesky/bluesky/jobs/544407127 

```
bluesky/tests/test_run_engine.py::test_sigint_three_hits 2.165500001183318e-05:  about to start the timers
0.001397149000013087:  all timers started
0.0014307630000303106:  about to start RE
0.008947329000022819:  about to move the motor
20:10:00.289796 set               -> motor           args: (1,), kwargs: {'group': 'b96d483a-608f-4475-b500-3fcfd6bcfc42'}
20:10:00.290584 wait              -> None            args: (), kwargs: {'group': 'b96d483a-608f-4475-b500-3fcfd6bcfc42'}
0.10844164100001308:  the 3 timer has fired
0.1085880830000292:  the 3 timer has fired
0.19820066800002678:  the 3 timer has fired
0.19827369400002226:  sig int 0 of timer 3
0.1983679290000282:  sig int 0 of timer 3
0.3009030250000251:  sig int 0 of timer 3
0.30096284699999387:  sig int 1 of timer 3
0.3011311790000377:  sig int 1 of timer 3
0.36018618299999616:  sig int 1 of timer 3
0.36028158800002075:  sig int 2 of timer 3
0.36042728900002885:  sig int 2 of timer 3
0.47929226700000527:  sig int 2 of timer 3
0.526253177000001:  should never see this
20:10:00.807115 set               -> motor           args: (0,), kwargs: {'group': '38f63df9-39da-4e8c-b271-b0ce3cde1111'}
20:10:00.808824 wait              -> None            args: (), kwargs: {'group': '38f63df9-39da-4e8c-b271-b0ce3cde1111'}
A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
FAILED
```

@ke-zhang-rd just posted the same logging from his local machine and which sees the expected interlacing the threads sending SIGINT and the handler processing them.  On travis our signal handler does not get to try to run until after the plan exits (?!)

Below is the output from linux py37 from travis:

```
bluesky/tests/test_run_engine.py::test_sigint_three_hits 1.1589999999728207e-05:  about to start the timers
0.0008325149999990344:  all timers started
0.0008778760000041075:  about to start RE
0.010462945000000445:  about to move the motor
20:00:26.160204 set               -> motor           args: (1,), kwargs: {'group': 'cf766f22-ba9a-4f76-9684-339598a06ab0'}
20:00:26.160809 wait              -> None            args: (), kwargs: {'group': 'cf766f22-ba9a-4f76-9684-339598a06ab0'}
0.05052740899999719:  the 3 timer has fired
0.10078029000000299:  sig int 0 of timer 3
0.10090165500000126:  the 3 timer has fired
A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
0.15089545899999735:  the 3 timer has fired
0.1512128530000041:  sig int 1 of timer 3
0.1512552500000055:  sig int 0 of timer 3
trying a second time
Pausing...
0.15361004599999717:  out of RE
0.15365809499999727:  about RE.abort
Aborting: running cleanup and marking exit_status as 'abort'...
20:00:26.305029 set               -> motor           args: (0,), kwargs: {'group': '5982fb78-29f1-45df-8490-b07fa4f6f6a0'}
20:00:26.305436 wait              -> None            args: (), kwargs: {'group': '5982fb78-29f1-45df-8490-b07fa4f6f6a0'}
0.2011454069999985:  sig int 0 of timer 3
0.20144797500000777:  sig int 2 of timer 3
0.2016413989999961:  sig int 1 of timer 3
0.25140500100000907:  sig int 1 of timer 3
0.2520113070000036:  sig int 2 of timer 3
0.3016852720000003:  sig int 2 of timer 3
[E 20:00:26.808 run_engine:1515] Run aborted
    Traceback (most recent call last):
      File "/home/travis/build/bluesky/bluesky/bluesky/run_engine.py", line 1391, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/home/travis/build/bluesky/bluesky/bluesky/preprocessors.py", line 501, in finalize_wrapper
        ret = yield from plan
      File "/home/travis/build/bluesky/bluesky/bluesky/tests/test_run_engine.py", line 605, in self_sig_int_plan
        yield from abs_set(motor, 1, wait=True)
      File "/home/travis/build/bluesky/bluesky/bluesky/plan_stubs.py", line 182, in abs_set
        yield Msg('wait', None, group=group)
    bluesky.utils.RequestAbort
0.6610389450000014:  done RE.abort
PASSED
```

**Comment by tacaswell** [comment]
From a run that has the corrected logging statements: https://travis-ci.org/bluesky/bluesky/jobs/544420254

```
bluesky/tests/test_run_engine.py::test_sigint_three_hits 2.2779000000028304e-05:  about to start the timers
0.0012184600000004764:  all timers started
0.001257187000000215:  about to start RE
0.006926855999999759:  about to move the motor
20:40:20.984767 set               -> motor           args: (1,), kwargs: {'group': '8ba66316-bc2c-486a-ad57-913c51f94f3e'}
20:40:20.985762 wait              -> None            args: (), kwargs: {'group': '8ba66316-bc2c-486a-ad57-913c51f94f3e'}
0.06163282300000006:  the 1 timer has fired
0.10121094500000005:  the 2 timer has fired
0.18148930799999974:  sig int 0 of timer 1
0.19133156000000007:  the 3 timer has fired
0.19140330000000105:  sig int 0 of timer 2
0.23743294199999987:  sig int 1 of timer 1
0.28283178500000083:  sig int 0 of timer 3
0.2829894750000008:  sig int 1 of timer 2
0.31806808099999984:  sig int 2 of timer 1
0.39514455099999957:  sig int 1 of timer 3
0.40407719500000105:  sig int 2 of timer 2
0.44766748300000003:  sig int 2 of timer 3
0.5191971140000007:  should never see this
20:40:21.497046 set               -> motor           args: (0,), kwargs: {'group': '911d33b4-6ff3-432e-ba39-d80576a00d74'}
20:40:21.497850 wait              -> None            args: (), kwargs: {'group': '911d33b4-6ff3-432e-ba39-d80576a00d74'}
A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
FAILED

```

**Comment by jklynch** [comment]
PASSED
bluesky/tests/test_run_engine.py::test_sigint_three_hits ***** the matplotlib backend is fQt5Agg *****
9.308000000096683e-06:  about to start the timers
0.0004045289999998758:  all timers started
0.0004239459999997308:  about to start RE
0.002077188999999535:  about to move the motor
17:43:51.602756 set               -> motor           args: (1,), kwargs: {'group': '4671e41c-9be2-4083-b73b-adb1d64385d1'}
17:43:51.603208 wait              -> None            args: (), kwargs: {'group': '4671e41c-9be2-4083-b73b-adb1d64385d1'}
0.05202421899999976:  the 1 timer has fired
0.1041943639999996:  the 2 timer has fired
0.10429732500000011:  sig int 0 of timer 1
A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
0.15470431600000012:  the 3 timer has fired
0.15581086400000022:  sig int 0 of timer 2
0.1558670659999999:  sig int 1 of timer 1
trying a second time
Pausing...
0.15757531199999963:  out of RE
0.15759606800000014:  about RE.abort
Aborting: running cleanup and marking exit_status as 'abort'...
17:43:51.759427 set               -> motor           args: (0,), kwargs: {'group': 'd8180e04-e235-44eb-845e-965b7eaae9a7'}
17:43:51.759911 wait              -> None            args: (), kwargs: {'group': 'd8180e04-e235-44eb-845e-965b7eaae9a7'}
0.20625512999999973:  sig int 0 of timer 3
0.20637433499999958:  sig int 2 of timer 1
0.20649121199999954:  sig int 1 of timer 2
0.25701259600000004:  sig int 1 of timer 3
0.2570994500000001:  sig int 2 of timer 2
0.31142166999999965:  sig int 2 of timer 3
[E 17:43:52.261 run_engine:1515] Run aborted
    Traceback (most recent call last):
      File "/Users/joshualynch/project/june_11_bs_test/bluesky/bluesky/run_engine.py", line 1391, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/Users/joshualynch/project/june_11_bs_test/bluesky/bluesky/preprocessors.py", line 501, in finalize_wrapper
        ret = yield from plan
      File "/Users/joshualynch/project/june_11_bs_test/bluesky/bluesky/tests/test_run_engine.py", line 611, in self_sig_int_plan
        yield from abs_set(motor, 1, wait=True)
      File "/Users/joshualynch/project/june_11_bs_test/bluesky/bluesky/plan_stubs.py", line 182, in abs_set
        yield Msg('wait', None, group=group)
    bluesky.utils.RequestAbort
0.6767906669999997:  done RE.abort

**Comment by tacaswell** [comment]
closing in favor of #1216

**Pull request closed without merging**
