### PR TITLE
apply suggestions to fix the xfail error and the case if no fields supplied

### PR DESCRIPTION
**Pull request by stan-dot**
Three lines change - adding a default value for fields, and removing pytest xfail lines

### CODE REVIEW

**Review by danielballan — APPROVED** [review]

**Comment by stan-dot** [comment]
@danielballan the xfail removal makes the tests fail, I think I forgot the minutiae of that part of the ticket - should the failing tests be removed or modified?

**Comment by tacaswell** [comment]
IIRC those tests should work, but they were xfailed because we broke our simulation tools so we should leave the tests alone and either fix or modify the simulated devices we are handing in.

**Comment by danielballan** [comment]
Discussion on call: Merge the change to BEC to fix that issue, but defer removing the `xfail` and fixing the simulation code to a separate issue.

**Comment by stan-dot** [comment]
limiting the PR to the default fields, to make the new issue for the xfail logic which interlaces with the ophyd.sim. 
`hw.det` (module in ophyd)

**Pull request merged**
