### PR TITLE
FIX: print_summary_wrapper was not forwarding all channels

### PR DESCRIPTION
**Pull request by tacaswell**
Was not passing values or exceptions back into the wrapped plan or
forwarding the return value out.

### CODE REVIEW

**Comment by danielballan** [comment]
This looks like a relevant test failure:

```
bluesky/tests/test_simulators.py::test_summary_wrapper_comms FAILED      [ 92%]
```

**Comment by danielballan** [comment]
Needs rebase and attention to failing test noted above.

**Comment by tacaswell** [comment]
The test failure was a missing import 🤦🏻 .

**Comment by tacaswell** [comment]
Fixed by https://github.com/bluesky/bluesky/pull/1627

**Pull request closed without merging**
