### PR TITLE
Move ophyd master build to 3.8.

### PR DESCRIPTION
**Pull request by danielballan**
For consideration.

### CODE REVIEW

**Comment by danielballan** [comment]
Decided against adding 3 more builds, but it would be better to test against the latest Python. Most likely to find issues.

**Comment by dmgav** [comment]
May be the test with Ophyd master should be allowed to fail?

**Comment by danielballan** [comment]
I'm slightly against allowing failures. Those can sometimes pass unnoticed.

I think we let Python nightly builds fail because we don't _control_ Python nightly, and we don't want temporary upstream problems to block merging bluesky PRs. But we do control ophyd `master`, and it may be useful to know right away if we introduce an incompatibility between ophyd and bluesky.

Thoughts?

**Comment by dmgav** [comment]
Yes, I think it can be done this way. But then it may be a good practice to manually check if Bluesky CI is still passing before merging Ophid PRs.

**Comment by danielballan** [comment]
Yes, I hope this would be last-resort alert. Ideally any changes to ophyd that could affect bluesky (especially changes to `ophyd.sim`) should be run against the bluesky test suite locally. Added a note in https://github.com/bluesky/ophyd/issues/822

**Pull request merged**
